image: danger89/gtk3-docker-cmake-ninja:2.2

stages:
  - test
  - build
  - release

static_code_analysis:
  stage: test
  script:
    - ./scripts/cpp_check.sh

# Build WineGUI + Doxygen
build:
  stage: build
  script: ./scripts/build_prod.sh
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 week
    paths:
      - doc/doxygen/
      - build_prod/WineGUI-*.deb
      - build_prod/WineGUI-*.rpm
      - build_prod/WineGUI-*.tar.gz
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build_prod/bin
      policy: push

# Upload the artifacts / release
release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - export APP_VERSION=${CI_COMMIT_TAG}
    - ./scripts/upload_release.sh
    - ./scripts/create_release_links.sh
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build_prod/bin
      policy: pull

#unit_test:
#  stage: test
#  script: ./build_prod/bin/runTests
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build_prod/bin/
